### PR TITLE
User banning frontend and fixes

### LINKED ISSUE #358: Expose ctfd ban behavior
- Allow admins to ban users
  - This will immediately invalidate all existing sessions for that user
  - This will prevent future logins with a user is banned message
  - Banned users shouldn't be able to use any user_endpoints, in case sessions don't get invalidated properly
- Expose a ban/unban button on the user admin panel. Maybe consider including a "reason" field
- Use the underlying ctfd user banned flag (https://github.com/CTFd/CTFd/blob/master/CTFd/models/__init__.py#L413)

- What happens to teams the banned user is on?
  - Nothing automatically I think - if captain is banned, admin can go assign somebody else manually

```
POST /admin/users/[id]/ban
POST /admin/uesrs/[id]/unban
```

### PR DESCRIPTION
**Pull request by trevnels-cs**
- Adds ban/unban modal to users on the frontend
- Adds missing table columns (`banned` and `affiliation`)
- Backend fixes
    - Deregister CTFd's `before_request_func` for ban checking (previously resulted in a 500 for banned users) to instead fall through to our ban logic/message
    - Disallow impersonating banned users (banned user can't do anything and can't exit impersonation, so you end up getting stuck and having to clear cookies to escape)

Closes #358

### CODE REVIEW

File: frontend/src/routes/admin/users/index.tsx [hunk 1]
```diff
@@ -46,6 +46,19 @@ const colDefs: ColDef<User>[] = [
     filter : true,
     floatingFilter : true,
   },
+  {
+    field : 'affiliation.name',
+    headerName : 'Affiliation',
```
Comment (cjones-cs) [inline frontend/src/routes/admin/users/index.tsx]: Change header name to "Sponsor"

**Review by cjones-cs — CHANGES_REQUESTED** [review]
Sponsor is the ui name. Affiliation is only used on the backend and will be changed in v2 to Sponsor

**Review by cjones-cs — APPROVED** [review]
